[project]
name = "pdftranslator"
version = "1.4.0"
description = "PDFを英語から日本語に翻訳"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "customtkinter>=5.2.2",
    "google-genai>=1.66.0",
    "keyring>=25.7.0",
    "openai>=2.26.0",
    "pyinstaller>=6.19.0",
    "pymupdf>=1.27.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]

[tool.pytest.ini_options]
pythonpath = "src"
testpaths = ["tests"]
